# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(max_length=3)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('job', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
